version: '3.2'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      PORT: ${PORT}
      MONGO_CONNECTION_STRING: ${MONGO_CONNECTION_STRING}
    volumes: 
      - .:/usr/src/
      - /usr/src/node_modules/
    container_name: go-net-api-test
    ports:
      - 4000:4000